export const cartTypes = {
  ADD_CART: 'ADD_CART',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  GET_NUMBER_CART: 'GET_NUMBER_CART',
  UPDATE_CART: 'UPDATE_CART',
  DELETE_CART: 'DELETE_CART',
};
