export const categoriesTypes = {
  FETCH_ALL_CATEGORIES_START: 'FETCH_ALL_CATEGORIES_START',
  FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
  FETCH_ALL_CATEGORIES_FAIL: 'FETCH_ALL_CATEGORIES_FAIL',
};
