export const filterCategoriesTypes = {
  FETCH_ALL_FILTER_CATEGORIES_START: 'FETCH_ALL_FILTER_CATEGORIES_START',
  FETCH_ALL_FILTER_CATEGORIES_SUCCESS: 'FETCH_ALL_FILTER_CATEGORIES_SUCCESS',
  FETCH_ALL_FILTER_CATEGORIES_FAIL: 'FETCH_ALL_FILTER_CATEGORIES_FAIL',
};
